services:
  - type: web
    name: bextractor
    runtime: python
    plan: starter
    buildCommand: ./build.sh
    startCommand: cd server && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_VERSION
        value: "20"
